services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317'
      - '4318'
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: '${IAM_DB_NAME:-iam}'
      POSTGRES_PASSWORD: '${IAM_DB_PASSWORD:-iam-local}'
      POSTGRES_USER: '${IAM_DB_USERNAME:-iam}'
    ports:
      - '5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"']
      interval: 10s
      timeout: 5s
      retries: 10
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
