spring:
  application:
    name: iam-core-service
  docker:
    compose:
      enabled: false
      file: compose.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  otlp:
    metrics:
      export:
        enabled: false
