spring:
  application:
    name: iam-core-service
  docker:
    compose:
      enabled: false
      file: compose.yaml
  flyway:
    baseline-on-migrate: false
    clean-disabled: true
    out-of-order: false
    validate-migration-naming: true
    validate-on-migrate: true
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  otlp:
    metrics:
      export:
        enabled: false
